[2023-04-11T00:34:03.465+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: api_dag.is_api_available scheduled__2023-04-10T00:00:00+00:00 [queued]>
[2023-04-11T00:34:03.505+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: api_dag.is_api_available scheduled__2023-04-10T00:00:00+00:00 [queued]>
[2023-04-11T00:34:03.510+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-04-11T00:34:03.516+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-04-11T00:34:03.522+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-04-11T00:34:03.553+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-04-10 00:00:00+00:00
[2023-04-11T00:34:03.580+0000] {standard_task_runner.py:55} INFO - Started process 30515 to run task
[2023-04-11T00:34:03.602+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'api_dag', 'is_api_available', 'scheduled__2023-04-10T00:00:00+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/api.py', '--cfg-path', '/tmp/tmpf3vdtwqd']
[2023-04-11T00:34:03.606+0000] {standard_task_runner.py:83} INFO - Job 106: Subtask is_api_available
[2023-04-11T00:34:03.924+0000] {task_command.py:376} INFO - Running <TaskInstance: api_dag.is_api_available scheduled__2023-04-10T00:00:00+00:00 [running]> on host c12a518d534c
[2023-04-11T00:34:04.128+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=api_dag
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-04-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-10T00:00:00+00:00
[2023-04-11T00:34:04.143+0000] {http.py:120} INFO - Poking: api/
[2023-04-11T00:34:04.169+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2023-04-11T00:34:04.222+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2023-04-11T00:34:04.649+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2023-04-11T00:34:04.712+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=api_dag, task_id=is_api_available, execution_date=20230410T000000, start_date=20230411T003403, end_date=20230411T003404
[2023-04-11T00:34:04.856+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-04-11T00:34:05.016+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-04-11T17:26:46.788+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: api_dag.is_api_available scheduled__2023-04-10T00:00:00+00:00 [queued]>
[2023-04-11T17:26:46.905+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: api_dag.is_api_available scheduled__2023-04-10T00:00:00+00:00 [queued]>
[2023-04-11T17:26:46.907+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-04-11T17:26:46.909+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-04-11T17:26:46.914+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-04-11T17:26:47.012+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-04-10 00:00:00+00:00
[2023-04-11T17:26:47.038+0000] {standard_task_runner.py:55} INFO - Started process 39702 to run task
[2023-04-11T17:26:47.061+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'api_dag', 'is_api_available', 'scheduled__2023-04-10T00:00:00+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/api.py', '--cfg-path', '/tmp/tmpa9nh4n0r']
[2023-04-11T17:26:47.092+0000] {standard_task_runner.py:83} INFO - Job 118: Subtask is_api_available
[2023-04-11T17:26:47.332+0000] {task_command.py:376} INFO - Running <TaskInstance: api_dag.is_api_available scheduled__2023-04-10T00:00:00+00:00 [running]> on host c12a518d534c
[2023-04-11T17:26:47.778+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=api_dag
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-04-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-10T00:00:00+00:00
[2023-04-11T17:26:47.788+0000] {http.py:120} INFO - Poking: api/
[2023-04-11T17:26:47.962+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2023-04-11T17:26:48.012+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2023-04-11T17:26:48.811+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2023-04-11T17:26:48.961+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=api_dag, task_id=is_api_available, execution_date=20230410T000000, start_date=20230411T172646, end_date=20230411T172648
[2023-04-11T17:26:49.411+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-04-11T17:26:49.661+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
