[2023-04-09T00:00:01.374+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: api_dag.create_table scheduled__2023-04-08T00:00:00+00:00 [queued]>
[2023-04-09T00:00:01.381+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: api_dag.create_table scheduled__2023-04-08T00:00:00+00:00 [queued]>
[2023-04-09T00:00:01.385+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-04-09T00:00:01.386+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-04-09T00:00:01.387+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-04-09T00:00:01.397+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2023-04-08 00:00:00+00:00
[2023-04-09T00:00:01.403+0000] {standard_task_runner.py:55} INFO - Started process 8521 to run task
[2023-04-09T00:00:01.407+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'api_dag', 'create_table', 'scheduled__2023-04-08T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/api.py', '--cfg-path', '/tmp/tmp0azwipjd']
[2023-04-09T00:00:01.410+0000] {standard_task_runner.py:83} INFO - Job 29: Subtask create_table
[2023-04-09T00:00:01.491+0000] {task_command.py:376} INFO - Running <TaskInstance: api_dag.create_table scheduled__2023-04-08T00:00:00+00:00 [running]> on host c12a518d534c
[2023-04-09T00:00:01.564+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=api_dag
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-04-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-08T00:00:00+00:00
[2023-04-09T00:00:01.578+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-04-09T00:00:01.585+0000] {sql.py:315} INFO - Running statement: CREATE TABLE IF NOT EXISTS user_details (
    firstname VARCHAR NOT NULL,
    lastname VARCHAR NOT NULL,
    country VARCHAR NOT NULL,
    username VARCHAR UNIQUE NOT NULL,
    password VARCHAR NOT NULL,
    email VARCHAR UNIQUE NOT NULL);, parameters: None
[2023-04-09T00:00:01.587+0000] {postgres.py:96} INFO - NOTICE:  relation "user_details" already exists, skipping

[2023-04-09T00:00:01.599+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=api_dag, task_id=create_table, execution_date=20230408T000000, start_date=20230409T000001, end_date=20230409T000001
[2023-04-09T00:00:01.660+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-04-09T00:00:01.686+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-04-11T17:26:32.287+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: api_dag.create_table scheduled__2023-04-08T00:00:00+00:00 [queued]>
[2023-04-11T17:26:32.309+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: api_dag.create_table scheduled__2023-04-08T00:00:00+00:00 [queued]>
[2023-04-11T17:26:32.317+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-04-11T17:26:32.318+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-04-11T17:26:32.320+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-04-11T17:26:32.379+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2023-04-08 00:00:00+00:00
[2023-04-11T17:26:32.393+0000] {standard_task_runner.py:55} INFO - Started process 39668 to run task
[2023-04-11T17:26:32.409+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'api_dag', 'create_table', 'scheduled__2023-04-08T00:00:00+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/api.py', '--cfg-path', '/tmp/tmpk9fl00c_']
[2023-04-11T17:26:32.414+0000] {standard_task_runner.py:83} INFO - Job 110: Subtask create_table
[2023-04-11T17:26:32.785+0000] {task_command.py:376} INFO - Running <TaskInstance: api_dag.create_table scheduled__2023-04-08T00:00:00+00:00 [running]> on host c12a518d534c
[2023-04-11T17:26:33.145+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=api_dag
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-04-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-08T00:00:00+00:00
[2023-04-11T17:26:33.213+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-04-11T17:26:33.235+0000] {sql.py:315} INFO - Running statement: Drop table user_details;

CREATE TABLE IF NOT EXISTS user_details (
    firstname VARCHAR NOT NULL,
    lastname VARCHAR NOT NULL,
    country VARCHAR NOT NULL,
    username VARCHAR UNIQUE NOT NULL,
    password VARCHAR NOT NULL,
    email VARCHAR UNIQUE NOT NULL);, parameters: None
[2023-04-11T17:26:33.309+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=api_dag, task_id=create_table, execution_date=20230408T000000, start_date=20230411T172632, end_date=20230411T172633
[2023-04-11T17:26:33.456+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-04-11T17:26:33.585+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
